// Donations
export const FETCH_DONATIONS_SUCCEED = 'FETCH_DONATIONS_SUCCEED';
export const FETCH_DONATIONS_FAILED = 'FETCH_DONATIONS_FAILED';
export const RESET_DONATIONS_INITIAL_STATE = 'RESET_DONATIONS_INITIAL_STATE';

//DonationRequest
export const UPDATE_DONATION_REQUEST_TITLE = 'UPDATE_DONATION_REQUEST_TITLE';
export const UPDATE_DONATION_REQUEST_DESCRIPTION = 'UPDATE_DONATION_REQUEST_DESCRIPTION';
export const UPDATE_DONATION_REQUEST_BLOODTYPE = 'UPDATE_DONATION_REQUEST_BLOODTYPE';
export const RESET_DONATION_REQUEST_INITIAL_STATE = 'RESET_DONATION_REQUEST_INITIAL_STATE';

export const CREATE_DONATION_REQUEST_SUCCEED = 'CREATE_DONATION_REQUEST_SUCCEED';
export const CREATE_DONATION_REQUEST_FAILED = 'CREATE_DONATION_REQUEST_FAILED';